### PR TITLE
pep8_fixes

### PR DESCRIPTION
**Pull request by the-zebulan**
I fixed the PEP8 issues in all of the files in `py_src` except:

* `chord.py` (as discussed in the previous PR)
* a single line in `py_src/test_utils.py`. I'm sure it could be split up like the other strings but with the various punctuation in the string I didn't want to mess up the command for the windows batch file (and I don't have a Windows computer to test the command).

I've been pushing these commits to my fork and checking the results on CodeClimate. Currently, the score is up to 3.0 GPA from 2.81 GPA.

* https://codeclimate.com/github/the-zebulan/p2p-project/compare/pep8_fixes

Let me know what you think!

### CODE REVIEW

**Comment by gappleto97** [comment]
I'll take a look in the morning. Git diff isn't telling me anything useful, because it thinks you rewrote the whole file. So I'll have to be awake for this (oh no!) 

The couple changes I did notice look good so far though. It's kind of hilarious that even after fixing 200+ issues, `base.py` still has >100 flagged. I really messed up XD

**Comment by gappleto97** [comment]
From what I saw this almost certainly gets merged. I'll want to try and fix some Javascript style stuff as well, just to merge all of it at once, but that's on my head.

**Comment by gappleto97** [comment]
To make sure though, you're:

1. Okay being listed in the authors section, and
2. Okay with it being licensed under me still, just in case I need to change the license at some point

Dolphin-emu had a really bad time with that last part, so I'd like to get ahead of it before it inevitably needs to happen.

**Comment by the-zebulan** [comment]
> Git diff isn't telling me anything useful, because it thinks you rewrote the whole file

I just looked at the diff now and realized what I did, it was the line-endings that were changed (I only really changed the PEP8 issue parts). I think the original files were using CRLF and when I loaded them in PyCharm it replaces them with LF (my default settings on Ubuntu). When I went to commit, I noticed it said I was using CRLF and I didn't realize why so I changed them back. I think PyCharm was trying to do the right thing by converting them back when I committed them but I overrode it without thinking about it (late night coding, my mistake). I can change the line-endings back to CRLF if you want?

> Okay being listed in the authors section

If you think that's appropriate, sure. I didn't really add much to the project so I'm ok if you don't want to list me there. I'm just trying to get more practice using git and GitHub so I win either way!

> Okay with it being licensed under me still, just in case I need to change the license at some point

No problem at all, I don't want to cause any issues with the licence with my style commits!

**Comment by the-zebulan** [comment]
> The couple changes I did notice look good so far though. It's kind of hilarious that even after fixing 200+ issues, `base.py` still has >100 flagged. I really messed up XD

I'm not sure you are correct there, I think `base.py` only has one issue left (the complexity one). I could be wrong but... it seems like the CodeClimate for my fork of your repo is only showing the `develop` branch but the changes I made were to a new branch, `pep8_fixes`.

https://codeclimate.com/github/the-zebulan/p2p-project/py_src/base.py

It shows 114 issues but 113 are PEP8 style issues which I fixed in the `pep8_fixes` branch.

**Comment by the-zebulan** [comment]
I just went through the files in the `py_src` directory on the `develop` branch to see what the original line-endings were for each file.

| Filename | CRLF | LF |
| --- | --- | --- |
| `test/__init__.py` | :ballot_box_with_check: |   |
| `test/test_base.py` |   | :ballot_box_with_check: |
| `test/test_cbase.py` |   | :ballot_box_with_check: |
| `test/test_chord.py` | :ballot_box_with_check: |   |
| `test/test_mesh.py` |   | :ballot_box_with_check: |
| `test/test_sync.py` |   | :ballot_box_with_check: |
| `test/test_utils.py` | :ballot_box_with_check: |   |
| `__init__.py` | :ballot_box_with_check: |   |
| `base.py` | :ballot_box_with_check: |   |
| `chord.py` | :ballot_box_with_check: |   |
| `kademlia.py` | :ballot_box_with_check: |   |
| `mesh.py` | :ballot_box_with_check: |   |
| `ssl_wrapper.py` |   | :ballot_box_with_check: |
| `sync.py` |   | :ballot_box_with_check: |
| `utils.py` | :ballot_box_with_check: |   |

In my PR, all of the files (except two) now have the line-endings set as `LF`. The two files that still have `CRLF` are `test/__init__.py` (because I didn't modify it) and `chord.py` (because you didn't want it modified, at least yet).

Since the line-endings don't seem to be consistent across the files in `py_src`, I'm not sure how to handle this particular issue.

* I could make them match the original file line-endings so the git diffs are much easier for you to see which changes I made. Then you could always change them afterwards to whatever line-ending you prefer.
* I could leave them all as `LF` (and even convert the line-endings in `test/__init__.py` and `chord.py`) for consistency.
* I could set them all to `CRLF` for consistency (maybe you use Windows to develop or just have `CRLF` set as your preferred line-ending?)

Let me know if you think I should make any modifications to this PR!

**Comment by gappleto97** [comment]
> it seems like the CodeClimate for my fork of your repo is only showing the develop branch but the changes I made were to a new branch, pep8_fixes.

Yeah, I ran into that bug before. Should have thought of that before I sounded silly.

>  I can change the line-endings back to CRLF if you want?

At some point I had Sublime (or maybe git) translating these to CRLF for me, but I've had to reimage my computers a few times since then. Probably this is where the inconsistencies occurred. If you changed that back to CRLF I'd say thank you. I occasionally need to work on Windows (yuck), so it's nice for it to be consistently that way.

**Comment by gappleto97** [comment]
Also, feel free to ignore the red light from Travis on the most recent test. It looks like `cryptography` installed wrong.

**Comment by the-zebulan** [comment]
Ok, quick question. Since some of the files had `LF` to begin with, if I change them back to `CRLF` then the git diff will be harder for you to read on those ones as well. Two ideas...

* I could make them match the `develop` branches original line-endings temporarily so that you could see/approve the changes I made. Then I could set them all to `CRLF` as you prefer before merging.
* Or, I could just switch every file in `py_src` to have `CRLF` line-endings. I have no problem doing this at all, I just don't want to cause you extra work in reading through the git diffs where it looks like the whole file has changed.

What do you think?

**Comment by gappleto97** [comment]
Just switch it all. I can deal with it on my end fairly easily.

**Comment by the-zebulan** [comment]
Ok, I'm on it.

**Comment by the-zebulan** [comment]
Looks like `README.rst` also has `LF`, should I switch that one too or just do the `.py` files?

**Comment by gappleto97** [comment]
Might as well leave the text files alone. I only really want to focus on the Python stuff for the moment.

**Comment by the-zebulan** [comment]
That last commit I pushed changed the line-endings in all of the Python files in `py_src` to `CRLF`. I did not touch the `README.rst`.

**Comment by gappleto97** [comment]
You're now merged. I'm going to make a quick update to the author section. Would you prefer your GitHub handle, or a name?

**Comment by the-zebulan** [comment]
Awesome! I'm glad you approved of the changes. Also, I'm fine with you just using my GitHub username for the author section.

Thanks again for your time and the merge!

**Comment by gappleto97** [comment]
No problem. I'd love it if you stuck around and helped more, not that I would demand it. There's a lot of code which could probably be cleaned up, and I'm going to have to work full time on `chord.py` if I want to make my release schedule.

**Comment by the-zebulan** [comment]
The only issue is that I don't have a lot of experience with any other language than Python (a little bit of JavaScript too, I guess) and I haven't really worked on any big projects yet either. 

I'm still learning about programming in general so I don't know if I'd be much help (your code seems fairly advanced compared to anything I usually write!).

**Comment by gappleto97** [comment]
Would it help if I gave a specific goal?

As for the other languages, feel free to leave that to me. ON some of them I don't know much of what I'm doing either. Golang especially.

**Comment by the-zebulan** [comment]
Ya, if you could point me in the right direction I could try and work towards goals. I'm trying to gain programming experience so any opportunity to practice/learn seems like a good idea to me!

**Comment by gappleto97** [comment]
Okay. 

As things stand, each `base_connection` is storing the most recent characters it received in a list. This is *horribly* inefficient. 

I would be very happy if you could refactor this to store this as `bytes` instead. I don't think it will be too crazy, since it's only used in that class and a little in its children, but there will likely be lots of bugs in the early part. 

I'll open a separate issue so that we don't pollute a closed one here.

**Pull request merged**
