### PR TITLE
PEP8_fixes

### PR DESCRIPTION
**Pull request by the-zebulan**
Fixed some PEP8 issues pointed out by CodeClimate

* Continuation line under-indented for visual indent (multiple)
* Continuation line over-indented for visual indent (multiple)
* Line too long (multiple)
* The backslash is redundant between brackets (multiple)
* Missing whitespace around operator
* Continuation line with same indent as next logical line (multiple)

Initial PR only modififed `chord.py` so some of the style choices around indentation and brackets instead of backslashes could be discussed/approved.

### CODE REVIEW

**Comment by the-zebulan** [comment]
I should have run CodeClimate on my fork first (I just did it now), I guess it doesn't like the line breaks before an operator!

I was reading PEP8 and thought it was the right thing to do but I can change them back.

https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator

**Comment by gappleto97** [comment]
I really appreciate all the effort you've put in. If I'd caught you earlier I would have warned that `chord.py` has a lot of churn to go through before it's stable, though. I'll probably merge this after I go through it, but I would definitely concentrate more on the other files before I looked here. 

#103 and #106 are still mission critical for that file, and I don't know how to translate the other implementations I've seen to work here yet. I got close a couple times, and the current setup is *mostly* stable for *small* networks, but still.

**Comment by gappleto97** [comment]
Seriously though, it's awesome that you did this.

**Comment by the-zebulan** [comment]
Oh, my mistake. Do you think I should just delete this PR or maybe just revert `chord.py` and keep this PR open but do the other files instead?

**Comment by gappleto97** [comment]
Either way is fine with me. If you'd rather, I'll take a look at `chord.py` and see if those changes should be kept. That way we waste as little effort as possible. Feels too much like looking a gift horse in the mouth otherwise. It needs to happen eventually anyhow.

**Comment by the-zebulan** [comment]
I don't mind closing this one and starting a new PR with the other files instead. I don't want to cause any unnecessary work for you, I just wanted to help out (very small way but still). Also, I find it amusing to get rid of PEP8 warnings in PyCharm, it's almost a game for me!

**Comment by gappleto97** [comment]
Haha, fair enough

**Pull request closed without merging**
